// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8pCBRjUl84wGKoMUMJw5uQ4kH9q8dp2c',
    appId: '1:98145424886:web:014729ee1fec83778be3d7',
    messagingSenderId: '98145424886',
    projectId: 'project-apollo-ff7d3',
    authDomain: 'project-apollo-ff7d3.firebaseapp.com',
    storageBucket: 'project-apollo-ff7d3.appspot.com',
    measurementId: 'G-7K2V48R1JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqoF7ON1aE9Kk9D1R0OuK2JcemNDfI9V8',
    appId: '1:98145424886:android:9a4abfa160a302f38be3d7',
    messagingSenderId: '98145424886',
    projectId: 'project-apollo-ff7d3',
    storageBucket: 'project-apollo-ff7d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa4K4NsJ4udQCOYUujmqBqeZmVGWkL7ds',
    appId: '1:98145424886:ios:8ea95438627692298be3d7',
    messagingSenderId: '98145424886',
    projectId: 'project-apollo-ff7d3',
    storageBucket: 'project-apollo-ff7d3.appspot.com',
    iosClientId:
        '98145424886-g5fl2mfqlvrmj7fok8qu234u3lc7uc7g.apps.googleusercontent.com',
    iosBundleId: 'com.apollo',
  );
}
